ADprojectteam1/Controllers/StoreClerkController.cs
using ADprojectteam1.DB;
using ADprojectteam1.Filter;
using ADprojectteam1.Models;
using ADprojectteam1.Service;
using PagedList;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ADprojectteam1.Controllers
{
    [StoreClerkFilter]
    public class StoreClerkController : Controller
    {
        // GET: StoreClerk
        public ActionResult TobeCollectList()
        {
           
            ////////////////////////////////////////////////////////Dispatch features
            ///Retrieve all reqitems need to be deal with
            List<ReqItem> lri = ReqItemData.GetAllReqItemApproved();
            List<ReqItem> slist = new List<ReqItem>();
            List<ReqItem> xlist = new List<ReqItem>();
            var itemIdset = new HashSet<int>(lri.Select(x => x.item.Id).ToList());
            var depIdset = new HashSet<int>(lri.Select(x => x.emp.department.Id).ToList());
            var empIdset = new HashSet<int>(lri.Select(x => x.emp.Id).ToList());
            List<List<List<ReqItem>>> lll = new List<List<List<ReqItem>>>();
            List<List<ReqItem>> ll = new List<List<ReqItem>>();
            Dictionary<int, Dictionary<int, int>> list = new Dictionary<int, Dictionary<int, int>>();
           

            foreach (int itemId in itemIdset)
            {
                slist = lri.Where(x=>x.item.Id==itemId).ToList();

                Dictionary<int, int> depmap = new Dictionary<int, int>();
                foreach (int depId in depIdset)
                {
                    
                    xlist = slist.Where(x => x.emp.department.Id == depId&&x.item.Id==itemId).ToList();
                     depmap.Add(depId,xlist.Select(x=>x.Quant).Sum());
                    foreach (int empId in empIdset)
                    {//ReqItemData.SetReqItemCollecting(empId, itemId);

                    }
                }
                list.Add(itemId,depmap);
               
            }
            
            ViewBag.Rlist = list;
            

            return View();
        }

        [HttpPost]
        public JsonResult ConfirmCollect(int Id, int quant)
        {
            Dictionary<int, int> collist = new Dictionary<int, int>();
            if (Session["collist"]!=null)
            collist=((Dictionary<int,int>)Session["collist"]);

            
            if (collist == null)
            {
                collist = new Dictionary<int, int>();
                collist.Add(Id,quant);
                
            }

            else 
            {
                if (collist.ContainsKey(Id)) collist[Id] = quant;
                else collist.Add(Id, quant);

            }
  
            Session["collist"] = collist;

            object new_q = new { };
            return Json(new_q, JsonRequestBehavior.AllowGet);

        }

        public ActionResult GenerateDelOrder()
        {


            Dictionary<int, int> collist = new Dictionary<int, int>();
            if (Session["collist"] != null)
                collist = (Dictionary<int, int>)Session["collist"];
            else
                Session["collist"] = new Dictionary<int,int>();

            
            List<ReqItem> lri = ReqItemData.GetAllReqItemApproved();
            var itemIdset = new HashSet<int>(collist.Keys);
            var depIdset = new HashSet<int>(lri.Select(x => x.emp.department.Id).ToList());
            List<ReqItem> slist = new List<ReqItem>();
            List<ReqItem> xlist = new List<ReqItem>();
            Dictionary<int, Dictionary<int, int>> list = new Dictionary<int, Dictionary<int, int>>();




            foreach (int depId in depIdset)
            {
                slist = lri.Where(x => x.emp.department.Id == depId).ToList();

                Dictionary<int, int> itemmap = new Dictionary<int, int>();
                foreach (int itemId in itemIdset)
                {

                    xlist = slist.Where(x => x.item.Id==itemId).ToList();
                    int quant= xlist.Select(x => x.Quant).Sum();
                    double price = StockCardData.GetLatestPriceByItem(ItemData.GetItemById(itemId));
                    if(quant!=0) itemmap.Add(itemId,quant);
                    DepOrderData.CreateDepOrder(depId,itemId,quant,price);

                    //Withdraw from stock
                    Item item = ItemData.GetItemById(itemId);
                    int balance = StockCardData.GetStockBalanceByItem(item);
                    StockCardData.WithdrawFromStockRecord(item,DateTime.Today,DepartmentData.GetDepById(depId),quant,balance);
                    int stockbalance = StockCardData.GetStockBalanceByItem(item);
                    
                    //if (stockbalance < item.ReorderLevel) Send Notification
                }
                list.Add(depId, itemmap);

            }
            ViewBag.Rlist = list;
            Session["plannedlist"] = list;
            

           
           
            return View();
        }

        [HttpPost]
        public JsonResult ChangePlan(int itemId, int depId, int quant)
        {
            int totalitemquant = 0;
            Dictionary<int, Dictionary<int, int>> plannedlist = new Dictionary<int, Dictionary<int, int>>();
            if (Session["plannedlist"] != null)
            { plannedlist = (Dictionary<int, Dictionary<int,int>>)Session["plannedlist"]; }

            if (plannedlist.ContainsKey(depId)&&plannedlist[depId].ContainsKey(itemId)) 
            {
                plannedlist[depId][itemId] = quant;
                

                foreach (int dId in plannedlist.Keys)
                {


                    foreach(int iId in plannedlist[dId].Keys)
                    {
                        int i = plannedlist[dId][iId];
                       if(iId==itemId) totalitemquant += plannedlist[dId][iId];

                    }
                }

            }

            

            Session["plannedlist"] = plannedlist;
            object new_amount = new { Id = itemId, quant = totalitemquant };

            return Json(new_amount, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult ConfirmDelOrder()
        {
            object result;
            Dictionary<int, Dictionary<int, int>> plannedlist = new Dictionary<int, Dictionary<int, int>>();
            if (Session["plannedlist"] != null) { plannedlist = (Dictionary<int, Dictionary<int, int>>)Session["plannedlist"]; }

            //Check if the collected quant is tally with deliver plan
            Dictionary<int, int> collist = (Dictionary<int, int>)Session["collist"];
            foreach (int itemId in collist.Keys)
            {
                int itemtotal = 0;
                foreach (int depId in plannedlist.Keys)
                {
                    foreach (int iId in plannedlist[depId].Keys)
                    { 
                        if(iId==itemId) itemtotal += plannedlist[depId][itemId]; 
                    }
                }
                if (itemtotal != collist[itemId])
                {
                    result = new { status = false };
                    return Json(result, JsonRequestBehavior.AllowGet);
                }
            }

            //Set ItemReq status and Dep Order status
            foreach (int depId in plannedlist.Keys)
            {
                bool notifystatus = false;
                foreach (int itemId in plannedlist[depId].Keys)
                {
                    DepOrderData.SetCollected(depId, itemId, plannedlist[depId][itemId]);

                    
                    foreach (int empId in DepartmentData.GetAllEmpByDepId(depId).Select(x => x.Id))
                    {

                        if (ReqItemData.SetReqItemCollected(empId, itemId)&&notifystatus==false)
                        {
                            
                            string emailaddress = EmployeeData.FindEmpById(empId).EmailAdd;
                            Task task = Task.Run(() =>
                            {
                                EmailNotification.SendNotificationEmailToEmployee(emailaddress,"Stationary Requisition Status Changed", "Your Stationary Requisition is under delivering");
                            });
                            notifystatus = true;
                        }


                    }
                }
            }
            result = new { status=true };
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CollectedDepOrder()
        {
            Dictionary<int, Dictionary<int, int>> plannedlist = new Dictionary<int, Dictionary<int, int>>();
            
            List<Department> ldep=DepartmentData.GetAllDep();
            
            //load the collected dep order
            
                foreach (int depId in ldep.Select(x => x.Id))
                {
                    List<DepOrder> listdp = DepOrderData.GetCollectedDepOrderByDepId(depId);

                Dictionary<int, int> dp = new Dictionary<int, int>();
                foreach (int itemId in listdp.Select(x => x.item.Id))
                    { 
                        dp.Add(itemId,listdp.Where(x=>x.item.Id==itemId).FirstOrDefault().collectedquant);
                        
                    }
                if (!plannedlist.ContainsKey(depId)) plannedlist.Add(depId, dp);
                else plannedlist[depId] = dp;
                }
                Session["plannedlist"] = plannedlist;
                            
            
            ViewBag.Rlist = plannedlist;
            Session.Remove("collist");
            Session.Remove("plannedlist");

            return View();

           
        }



        /////////////////////////////////////////////////////////////////////////ReOrder features
        public ActionResult TobeReOrderList()
        {
            ItemData.SetSupplier();

ADprojectteam1/Views/StoreClerk/ApprovedRequisitionList.cshtml
@{
    ViewBag.Title = "ApprovedRequisitionList";
}

<h2>ApprovedRequisitionList</h2>

ADprojectteam1/Views/StoreClerk/CollectedDepOrder.cshtml
@using ADprojectteam1.Models;
@using ADprojectteam1.DB;

@{
    ViewBag.Title = "Collected Department Order List";
    Dictionary<int, Dictionary<int, int>> reqlist = ViewBag.Rlist;

}

<div class="row" style="padding-top:0px;">
    <div class="col-sm-3 col-xs-3 col-lg-3 col-md-3">
        @{
            Html.RenderPartial("_Layout_StoreClerk_LeftBar");
        }
    </div>

    <div class="w3-main" style="margin-left:250px">

        <h2>Collected Department Order List</h2>

        @{ if (reqlist.Count != 0)
            {
                <table class="w3-table w3-striped">
                    <tr><th>Dep Name</th><th>Collect Point</th><th>Contact Person</th></tr>

                    @{ foreach (int depId in reqlist.Keys)
                        {
                            if (reqlist[depId].Values.Sum() != 0)
                            {
                                <tr>
                                    <td>@DepartmentData.GetDepNameById(depId)</td>
                                    <td>@DepartmentData.GetColPointById(depId)</td>
                                    <td>@DepartmentData.GetContactNameById(depId)</td>

                                </tr>

                                <tr>
                                    <td>
                                        <table class="w3-table w3-striped">
                                            <tr><th>Item Name </th><th>Plan to Deli Quant</th><th>UOM</th></tr>

                                            @{ foreach (int itemId in reqlist[depId].Keys)
                                                {
                                                    <tr>
                                                        <td>@ItemData.GetItemById(itemId).Description</td>
                                                        <td>@reqlist[depId][itemId].</td>
                                                        <td>@ItemData.GetItemById(itemId).UnitofMeasure</td>
                                                    </tr>

                                                }
                                            }
                                        </table>
                                    </td>
                                </tr>
                            }


                        }
                    }

                </table>
                <br>

            }
            else{<h4>You haven't confirmed any delivery plan yet.</h4>}
        }
        <br>
    </div>
    </div>
 

ADprojectteam1/Views/StoreClerk/GenerateDelOrder.cshtml
@using ADprojectteam1.Models;
@using ADprojectteam1.DB;

@{
    ViewBag.Title = "Delivery Order List";
    Dictionary<int, Dictionary<int, int>> reqlist = ViewBag.Rlist;
    Dictionary<int, int> collist = (Dictionary<int, int>)Session["collist"];
    Dictionary<int, Dictionary<int,int>> planlist = (Dictionary<int, Dictionary<int,int>>)Session["plannedlist"];
}

    <div class="row" style="padding-top:0px;">
        <div class="col-sm-3 col-xs-3 col-lg-3 col-md-3">
            @{
                Html.RenderPartial("_Layout_StoreClerk_LeftBar");
            }
        </div>

        <div class="w3-main" style="margin-left:250px">
            <h2>Making delivery plan base on collected items.</h2>
            @{ if (planlist.Count != 0)
                {<h2>Overall Item Collected</h2>
                    <table class="w3-table w3-striped">
                        <tr><th>Item Name</th><th>Collected Quant</th><th>Planned Quant</th></tr>
                        @{ foreach (int itemId in collist.Keys)
                            {
                                <tr>
                                    <td>@ItemData.GetItemById(itemId).Description</td>

                                    <td>@collist[itemId]</td>
                                    <td><span id="plannedtotalq @itemId"></span></td>
                                </tr>


                            }
                            <tr>


                                <td><input type="button" value="Confirm Delivery Order" onclick="ConfirmDelOrder()" /></td>

                            </tr>

                        }
                    </table>
                    <br>

                    <h2>Delivery Order List</h2>

                    <table class="w3-table w3-striped">
                        <tr><th>Dep Name</th><th>Collect Point</th><th>Contact Person</th></tr>

                        @{ foreach (int depId in reqlist.Keys)
                            {
                                <tr>
                                    <td>@DepartmentData.GetDepNameById(depId)</td>
                                    <td>@DepartmentData.GetColPointById(depId)</td>
                                    <td>@DepartmentData.GetContactNameById(depId)</td>

                                </tr>

                                <tr>
                                    <td>
                                        <table class="w3-table w3-striped">
                                            <tr><th>Item Name </th><th>Demand Quant</th><th>Plan to Deli Quant</th></tr>

                                            @{ foreach (int itemId in reqlist[depId].Keys)
                                                {
                                                    <tr>
                                                        <td>@ItemData.GetItemById(itemId).Description</td>
                                                        <td>@reqlist[depId][itemId].</td>
                                                        <td><input type="text" placeholder="Input quantity" onchange="ChangePlan(@itemId,@depId)" size="6" id="PlanquantityBox @itemId@depId" value="@planlist[depId][itemId]"></td>
                                                    </tr>

                                                }
                                            }
                                        </table>
                                    </td>
                                </tr>

                            }
                        }
                    </table>
                }
                else
                { <h4>You haven't collected any item to make delivery plan yet. </h4>}
            }
            <br>
            <br>
        </div>
        </div>
            <script>

                function ChangePlan(itemId, depId) {


                    var q = document.getElementById("PlanquantityBox " + itemId + depId).value

                    var pdata = {
                        itemId: itemId, depId: depId, quant: q
                    };



                    $.ajax({
                        type: "POST",
                        url: "/StoreClerk/ChangePlan",
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(pdata),
                        dataType: "json",

                        // Response Success
                        success: function (response) {

                            
                            document.getElementById("plannedtotalq " + response.Id).innerHTML = response.quant;

                        },

                        // Response Fail
                        failure: function (response) {
                            alert("Fail Case");
                        },

                        // Response Error
                        error: function (response) {
                            alert("ERROR case");
                        }


                    });
                }

                function ConfirmDelOrder() {


                    

                    var pdata = {
                      
                    };



                    $.ajax({
                        type: "POST",
                        url: "/StoreClerk/ConfirmDelOrder",
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(pdata),
                        dataType: "json",

                        // Response Success
                        success: function (response) {

                            if (response.status == false) {
                                alert("The plan quantity is inconsistence with collected quantity.");
                            }
                            else {
                                alert("Confirm Delivery Order successfully");
                                window.location.href = "./CollectedDepOrder";
                            }

                        },

                        // Response Fail
                        failure: function (response) {
                            alert("Fail Case");
                        },

                        // Response Error
                        error: function (response) {
                            alert("ERROR case");
                        }


                    });
                }
            </script>

ADprojectteam1/Views/StoreClerk/TobeCollectList.cshtml
@using ADprojectteam1.Models;
@using ADprojectteam1.DB;

@{
    ViewBag.Title = "TobeCollectList";
    Dictionary<int, Dictionary<int, int>> reqlist = ViewBag.Rlist;
    Dictionary<int, int> collist = (Dictionary<int, int>)Session["collist"];
}

    <div class="row" style="padding-top:0px;">
        <div class="col-sm-3 col-xs-3 col-lg-3 col-md-3">
            @{
                Html.RenderPartial("_Layout_StoreClerk_LeftBar");
            }
        </div>

        <div class="w3-main" style="margin-left:250px">


            <h2>Collected Item List</h2>
            @{if (collist!=null&&collist.Count != 0)
                {


                    <table class="w3-table w3-striped">
                        <tr><th>Item Name</th><th>Quant</th></tr>

                        @{ foreach (int itemId in collist.Keys)
                            {
                                <tr>
                                    <td>@ItemData.GetItemById(itemId).Description</td>
                                    <td>@collist[itemId]</td>
                                    <td><input type="button" value="Delete" onclick="location.href='@Url.Action("deleteColItem", "StoreClerk", new { id = itemId })'" /></td>
                                </tr>

                            }
                        }
                    </table>
                    <input type="button" value="Generate Delivery Orders" onclick="location.href='@Url.Action("GenerateDelOrder", "StoreClerk")'" />
                }
                else
                { <h4>You haven't collected any item yet.</h4>}
            }


            <h2>TobeCollectList</h2>

            @{ if (reqlist.Count != 0)
                {<table class="w3-table w3-striped">
                        <tr><th>Item Name</th><th>Demand Quant</th><th>Collected Quant</th></tr>

                        @{ foreach (int itemId in reqlist.Keys)
                            {
                                <tr>
                                    <td>@ItemData.GetItemById(itemId).Description</td>
                                    <td>@reqlist[itemId].Values.Sum()</td>
                                    <td><input type="text" placeholder="Input quantity" size="6" id="ActquantityBox @itemId"></td>
                                    <td><input type="button" value="Confirm Collected" onclick="ConfirmCollect(@itemId);" /></td>
                                </tr>

                                <tr>
                                    <td>
                                        <table class="w3-table w3-striped">
                                            <tr><th>Department </th><th>Demand Quant</th></tr>

                                            @{ foreach (int depId in reqlist[itemId].Keys)
                                                {
                                                    if (@reqlist[itemId][depId] != 0)
                                                    {
                                                        <tr>
                                                            <td>@DepartmentData.GetDepNameById(depId)</td>
                                                            <td>@reqlist[itemId][depId]</td>

                                                        </tr>
                                                    }

                                                }
                                            }
                                        </table>
                                    </td>
                                </tr>

                                                }
                        }
                    </table>
                    <br> }
               else
               { <h4>There is no pending requisition to be collected now.</h4> }
            }

            <br>
        </div>
        </div>
            <script>

                function ConfirmCollect(itemId) {


                    var q = document.getElementById("ActquantityBox " + itemId).value

                    var pdata = {
                        Id: itemId, quant: q
                    };



                    $.ajax({
                        type: "POST",
                        url: "/StoreClerk/ConfirmCollect",
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(pdata),
                        dataType: "json",

                        // Response Success
                        success: function (response) {

                            alert("Confirm collection successfully");
                            window.location.href = "./TobeCollectList";

                        },

                        // Response Fail
                        failure: function (response) {
                            alert("Fail Case");
                        },

                        // Response Error
                        error: function (response) {
                            alert("ERROR case");
                        }


                    });
                }
            </script>

ADprojectteam1/Views/StoreClerk/TobeReOrderList.cshtml
@using ADprojectteam1.Models;
@using ADprojectteam1.DB;

@{
    ViewBag.Title = "Items TobeReOrder";
    List<Item> list = ViewBag.Rlist;
    Dictionary<int, int> sellist = (Dictionary<int, int>)Session["selectedsupplier"];
}

    <div class="row" style="padding-top:0px;">
        <div class="col-sm-3 col-xs-3 col-lg-3 col-md-3">
            @{
                Html.RenderPartial("_Layout_StoreClerk_LeftBar");
            }
        </div>

        <div class="w3-main" style="margin-left:250px">

            <h2>To be Re-order List</h2>

            @{ if (list.Count != 0)
                {
                    <input type="button" value="Generate Purchase Orders" onclick="GeneratePO()" />

                    <table class="w3-table w3-striped">
                        <tr><th>Item Name</th></tr>

                        @{ foreach (Item item in list)
                            {
                                <tr>
                                    <td>@item.Description</td>
                                    <td>
                                        <table class="w3-table w3-striped">
                                            <tr><th>Supplier Name</th><th>Unit Price</th><th>UOM</th></tr>
                                            <tr>
                                                <td>@item.Supplier1.supplier.Name</td>
                                                <td>@item.Supplier1.UnitPrice</td>
                                                <td>@item.UnitofMeasure</td>
                                            </tr>

                                            <tr>
                                                <td>@item.Supplier2.supplier.Name</td>
                                                <td>@item.Supplier2.UnitPrice</td>
                                                <td>@item.UnitofMeasure</td>
                                            </tr>

                                            <tr>
                                                <td>@item.Supplier3.supplier.Name</td>
                                                <td>@item.Supplier3.UnitPrice</td>
                                                <td>@item.UnitofMeasure</td>
                                            </tr>

                                        </table>

                                    </td>

                                    <td>
                                        <select style="width:350px;" id="supId" onchange="SelectSup(@item.Id)">
                                            @{

                                                <option value="@item.Supplier1.supplier.Id">@item.Supplier1.supplier.Name</option>
                                                <option value="@item.Supplier2.supplier.Id">@item.Supplier2.supplier.Name</option>
                                                <option value="@item.Supplier3.supplier.Id">@item.Supplier3.supplier.Name</option>

                                            }
                                        </select>
                                    </td>
                                </tr>
                                                }
                        }
                    </table>
                    <br>
                                                }
                                                else { <h4>There is no item's stock balance is below re-order level now.</h4>}
            }

            <br>
        </div>
        </div>

            <script>

                function SelectSup(itemId) {

                    var s = document.getElementById("supId");
                    var sId = s.options[s.selectedIndex].value;



                    var pdata = {
                        itemId: itemId, sId: sId
                    };



                    $.ajax({
                        type: "POST",
                        url: "/StoreClerk/SelectSupplier",
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(pdata),
                        dataType: "json",

                        // Response Success
                        success: function (response) {

                            alert("Selected supplier successfully");


                        },

                        // Response Fail
                        failure: function (response) {
                            alert("Fail Case");
                        },

                        // Response Error
                        error: function (response) {
                            alert("ERROR case");
                        }


                    });
                }

                function GeneratePO() {


                    var pdata = {

                    };



                    $.ajax({
                        type: "POST",
                        url: "/StoreClerk/GeneratePendingPO",
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(pdata),
                        dataType: "json",

                        // Response Success
                        success: function (response) {

                            alert("Generated Purchase Order successfully");
                            window.location.href = "./TobeReOrderList";

                        },

                        // Response Fail
                        failure: function (response) {
                            alert("Fail Case");
                        },

                        // Response Error
                        error: function (response) {
                            alert("ERROR case");
                        }


                    });
                }
            </script>